<?php


namespace App\Repostories;

use Illuminate\Bus\DatabaseBatchRepository;
use Illuminate\Bus\PendingBatch;
use Illuminate\Support\Facades\Auth;

class BatchRepository extends DatabaseBatchRepository
{
    public function store(PendingBatch $batch)
    {
        $batch = parent::store($batch); // TODO: Change the autogenerated stub

        $this->connection->table($this->table)
            ->where('id', $batch->id)->update([
                'user_id' => Auth::user()->id,
            ]);

        return $batch;
    }
    public function toBatch($batch)
    {
        return parent::toBatch($batch);
    }
}
